/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\scene.glb --types 
*/

"use client";

import type React from "react";
import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["sea_​​village900"]: THREE.Mesh;
    ["sea_​​village899"]: THREE.Mesh;
    ["sea_​​village898"]: THREE.Mesh;
    ["sea_​​village897"]: THREE.Mesh;
    ["sea_​​village896"]: THREE.Mesh;
    ["sea_​​village895"]: THREE.Mesh;
    ["sea_​​village894"]: THREE.Mesh;
    ["sea_​​village893"]: THREE.Mesh;
    ["sea_​​village892"]: THREE.Mesh;
    ["sea_​​village891"]: THREE.Mesh;
    ["sea_​​village890"]: THREE.Mesh;
    ["sea_​​village889"]: THREE.Mesh;
    ["sea_​​village888"]: THREE.Mesh;
    ["sea_​​village887"]: THREE.Mesh;
    ["sea_​​village886"]: THREE.Mesh;
    ["sea_​​village885"]: THREE.Mesh;
    ["sea_​​village884"]: THREE.Mesh;
    ["sea_​​village883"]: THREE.Mesh;
    ["sea_​​village882"]: THREE.Mesh;
    ["sea_​​village881"]: THREE.Mesh;
    ["sea_​​village880"]: THREE.Mesh;
    ["sea_​​village879"]: THREE.Mesh;
    ["sea_​​village878"]: THREE.Mesh;
    ["sea_​​village877"]: THREE.Mesh;
    ["sea_​​village876"]: THREE.Mesh;
    ["sea_​​village875"]: THREE.Mesh;
    ["sea_​​village874"]: THREE.Mesh;
    ["sea_​​village873"]: THREE.Mesh;
    ["sea_​​village872"]: THREE.Mesh;
    ["sea_​​village871"]: THREE.Mesh;
    ["sea_​​village870"]: THREE.Mesh;
    ["sea_​​village869"]: THREE.Mesh;
    ["sea_​​village868"]: THREE.Mesh;
    ["sea_​​village867"]: THREE.Mesh;
    ["sea_​​village866"]: THREE.Mesh;
    ["sea_​​village865"]: THREE.Mesh;
    ["sea_​​village864"]: THREE.Mesh;
    ["sea_​​village863"]: THREE.Mesh;
    ["sea_​​village862"]: THREE.Mesh;
    ["sea_​​village861"]: THREE.Mesh;
    ["sea_​​village860"]: THREE.Mesh;
    ["sea_​​village859"]: THREE.Mesh;
    ["sea_​​village858"]: THREE.Mesh;
    ["sea_​​village857"]: THREE.Mesh;
    ["sea_​​village856"]: THREE.Mesh;
    ["sea_​​village855"]: THREE.Mesh;
    ["sea_​​village854"]: THREE.Mesh;
    ["sea_​​village853"]: THREE.Mesh;
    ["sea_​​village852"]: THREE.Mesh;
    ["sea_​​village851"]: THREE.Mesh;
    ["sea_​​village850"]: THREE.Mesh;
    ["sea_​​village849"]: THREE.Mesh;
    ["sea_​​village848"]: THREE.Mesh;
    ["sea_​​village847"]: THREE.Mesh;
    ["sea_​​village846"]: THREE.Mesh;
    ["sea_​​village845"]: THREE.Mesh;
    ["sea_​​village844"]: THREE.Mesh;
    ["sea_​​village843"]: THREE.Mesh;
    ["sea_​​village842"]: THREE.Mesh;
    ["sea_​​village841"]: THREE.Mesh;
    ["sea_​​village840"]: THREE.Mesh;
    ["sea_​​village839"]: THREE.Mesh;
    ["sea_​​village838"]: THREE.Mesh;
    ["sea_​​village837"]: THREE.Mesh;
    ["sea_​​village836"]: THREE.Mesh;
    ["sea_​​village835"]: THREE.Mesh;
    ["sea_​​village834"]: THREE.Mesh;
    ["sea_​​village833"]: THREE.Mesh;
    ["sea_​​village832"]: THREE.Mesh;
    ["sea_​​village831"]: THREE.Mesh;
    ["sea_​​village830"]: THREE.Mesh;
    ["sea_​​village829"]: THREE.Mesh;
    ["sea_​​village828"]: THREE.Mesh;
    ["sea_​​village827"]: THREE.Mesh;
    ["sea_​​village826"]: THREE.Mesh;
    ["sea_​​village825"]: THREE.Mesh;
    ["sea_​​village824"]: THREE.Mesh;
    ["sea_​​village823"]: THREE.Mesh;
    ["sea_​​village822"]: THREE.Mesh;
    ["sea_​​village821"]: THREE.Mesh;
    ["sea_​​village820"]: THREE.Mesh;
    ["sea_​​village819"]: THREE.Mesh;
    ["sea_​​village818"]: THREE.Mesh;
    ["sea_​​village817"]: THREE.Mesh;
    ["sea_​​village816"]: THREE.Mesh;
    ["sea_​​village815"]: THREE.Mesh;
    ["sea_​​village814"]: THREE.Mesh;
    ["sea_​​village813"]: THREE.Mesh;
    ["sea_​​village812"]: THREE.Mesh;
    ["sea_​​village811"]: THREE.Mesh;
    ["sea_​​village810"]: THREE.Mesh;
    ["sea_​​village809"]: THREE.Mesh;
    ["sea_​​village808"]: THREE.Mesh;
    ["sea_​​village807"]: THREE.Mesh;
    ["sea_​​village806"]: THREE.Mesh;
    ["sea_​​village805"]: THREE.Mesh;
    ["sea_​​village804"]: THREE.Mesh;
    ["sea_​​village803"]: THREE.Mesh;
    ["sea_​​village802"]: THREE.Mesh;
    ["sea_​​village801"]: THREE.Mesh;
    ["sea_​​village800"]: THREE.Mesh;
    ["sea_​​village799"]: THREE.Mesh;
    ["sea_​​village798"]: THREE.Mesh;
    ["sea_​​village797"]: THREE.Mesh;
    island3_house_3: THREE.Mesh;
    island3_house_2: THREE.Mesh;
    ["sea_​​village794"]: THREE.Mesh;
    island3_chapelle: THREE.Mesh;
    ["sea_​​village792"]: THREE.Mesh;
    ["sea_​​village791"]: THREE.Mesh;
    ["sea_​​village790"]: THREE.Mesh;
    ["sea_​​village789"]: THREE.Mesh;
    ["sea_​​village788"]: THREE.Mesh;
    ["sea_​​village787"]: THREE.Mesh;
    ["sea_​​village786"]: THREE.Mesh;
    ["sea_​​village785"]: THREE.Mesh;
    ["sea_​​village784"]: THREE.Mesh;
    ["sea_​​village783"]: THREE.Mesh;
    ["sea_​​village782"]: THREE.Mesh;
    ["sea_​​village781"]: THREE.Mesh;
    ["sea_​​village780"]: THREE.Mesh;
    ["sea_​​village779"]: THREE.Mesh;
    ["sea_​​village778"]: THREE.Mesh;
    ["sea_​​village777"]: THREE.Mesh;
    ["sea_​​village776"]: THREE.Mesh;
    ["sea_​​village775"]: THREE.Mesh;
    ["sea_​​village774"]: THREE.Mesh;
    ["sea_​​village773"]: THREE.Mesh;
    ["sea_​​village772"]: THREE.Mesh;
    ["sea_​​village771"]: THREE.Mesh;
    ["sea_​​village770"]: THREE.Mesh;
    ["sea_​​village769"]: THREE.Mesh;
    ["sea_​​village768"]: THREE.Mesh;
    ["sea_​​village762"]: THREE.Mesh;
    ["sea_​​village761"]: THREE.Mesh;
    ["sea_​​village760"]: THREE.Mesh;
    ["sea_​​village759"]: THREE.Mesh;
    ["sea_​​village758"]: THREE.Mesh;
    ["sea_​​village662"]: THREE.Mesh;
    ["sea_​​village661"]: THREE.Mesh;
    ["sea_​​village660"]: THREE.Mesh;
    ["sea_​​village659"]: THREE.Mesh;
    ["sea_​​village658"]: THREE.Mesh;
    ["sea_​​village657"]: THREE.Mesh;
    ["sea_​​village656"]: THREE.Mesh;
    ["sea_​​village655"]: THREE.Mesh;
    ["sea_​​village654"]: THREE.Mesh;
    ["sea_​​village653"]: THREE.Mesh;
    ["sea_​​village652"]: THREE.Mesh;
    ["sea_​​village651"]: THREE.Mesh;
    ["sea_​​village650"]: THREE.Mesh;
    ["sea_​​village649"]: THREE.Mesh;
    ["sea_​​village648"]: THREE.Mesh;
    ["sea_​​village647"]: THREE.Mesh;
    ["sea_​​village646"]: THREE.Mesh;
    ["sea_​​village645"]: THREE.Mesh;
    ["sea_​​village644"]: THREE.Mesh;
    ["sea_​​village643"]: THREE.Mesh;
    ["sea_​​village642"]: THREE.Mesh;
    ["sea_​​village641"]: THREE.Mesh;
    ["sea_​​village640"]: THREE.Mesh;
    ["sea_​​village639"]: THREE.Mesh;
    ["sea_​​village638"]: THREE.Mesh;
    ["sea_​​village637"]: THREE.Mesh;
    ["sea_​​village636"]: THREE.Mesh;
    ["sea_​​village635"]: THREE.Mesh;
    ["sea_​​village634"]: THREE.Mesh;
    ["sea_​​village633"]: THREE.Mesh;
    ["sea_​​village632"]: THREE.Mesh;
    ["sea_​​village631"]: THREE.Mesh;
    ["sea_​​village630"]: THREE.Mesh;
    ["sea_​​village629"]: THREE.Mesh;
    ["sea_​​village628"]: THREE.Mesh;
    ["sea_​​village627"]: THREE.Mesh;
    ["sea_​​village626"]: THREE.Mesh;
    ["sea_​​village625"]: THREE.Mesh;
    ["sea_​​village622"]: THREE.Mesh;
    ["sea_​​village621"]: THREE.Mesh;
    ["sea_​​village620"]: THREE.Mesh;
    ["sea_​​village619"]: THREE.Mesh;
    ["sea_​​village618"]: THREE.Mesh;
    ["sea_​​village617"]: THREE.Mesh;
    ["sea_​​village616"]: THREE.Mesh;
    ["sea_​​village602"]: THREE.Mesh;
    ["sea_​​village599"]: THREE.Mesh;
    ["sea_​​village598"]: THREE.Mesh;
    ["sea_​​village597"]: THREE.Mesh;
    ["sea_​​village596"]: THREE.Mesh;
    ["sea_​​village595"]: THREE.Mesh;
    ["sea_​​village594"]: THREE.Mesh;
    ["sea_​​village593"]: THREE.Mesh;
    ["sea_​​village592"]: THREE.Mesh;
    ["sea_​​village591"]: THREE.Mesh;
    ["sea_​​village590"]: THREE.Mesh;
    ["sea_​​village589"]: THREE.Mesh;
    ["sea_​​village543"]: THREE.Mesh;
    ["sea_​​village542"]: THREE.Mesh;
    ["sea_​​village531"]: THREE.Mesh;
    ["sea_​​village530"]: THREE.Mesh;
    ["sea_​​village525"]: THREE.Mesh;
    ["sea_​​village524"]: THREE.Mesh;
    ["sea_​​village398"]: THREE.Mesh;
    ["sea_​​village397"]: THREE.Mesh;
    ["sea_​​village396"]: THREE.Mesh;
    ["sea_​​village395"]: THREE.Mesh;
    ["sea_​​village394"]: THREE.Mesh;
    ["sea_​​village393"]: THREE.Mesh;
    ["sea_​​village392"]: THREE.Mesh;
    ["sea_​​village391"]: THREE.Mesh;
    ["sea_​​village390"]: THREE.Mesh;
    ["sea_​​village389"]: THREE.Mesh;
    ["sea_​​village388"]: THREE.Mesh;
    ["sea_​​village387"]: THREE.Mesh;
    ["sea_​​village386"]: THREE.Mesh;
    ["sea_​​village385"]: THREE.Mesh;
    ["sea_​​village384"]: THREE.Mesh;
    ["sea_​​village383"]: THREE.Mesh;
    ["sea_​​village382"]: THREE.Mesh;
    ["sea_​​village381"]: THREE.Mesh;
    ["sea_​​village380"]: THREE.Mesh;
    ["sea_​​village379"]: THREE.Mesh;
    ["sea_​​village378"]: THREE.Mesh;
    ["sea_​​village377"]: THREE.Mesh;
    ["sea_​​village376"]: THREE.Mesh;
    ["sea_​​village375"]: THREE.Mesh;
    ["sea_​​village374"]: THREE.Mesh;
    ["sea_​​village373"]: THREE.Mesh;
    ["sea_​​village372"]: THREE.Mesh;
    ["sea_​​village371"]: THREE.Mesh;
    ["sea_​​village370"]: THREE.Mesh;
    ["sea_​​village342"]: THREE.Mesh;
    ["sea_​​village341"]: THREE.Mesh;
    ["sea_​​village340"]: THREE.Mesh;
    ["sea_​​village339"]: THREE.Mesh;
    ["sea_​​village338"]: THREE.Mesh;
    ["sea_​​village337"]: THREE.Mesh;
    ["sea_​​village336"]: THREE.Mesh;
    ["sea_​​village335"]: THREE.Mesh;
    ["sea_​​village334"]: THREE.Mesh;
    ["sea_​​village333"]: THREE.Mesh;
    ["sea_​​village332"]: THREE.Mesh;
    ["sea_​​village331"]: THREE.Mesh;
    ["sea_​​village330"]: THREE.Mesh;
    ["sea_​​village329"]: THREE.Mesh;
    ["sea_​​village327"]: THREE.Mesh;
    ["sea_​​village326"]: THREE.Mesh;
    ["sea_​​village325"]: THREE.Mesh;
    ["sea_​​village324"]: THREE.Mesh;
    ["sea_​​village323"]: THREE.Mesh;
    ["sea_​​village322"]: THREE.Mesh;
    ["sea_​​village321"]: THREE.Mesh;
    ["sea_​​village320"]: THREE.Mesh;
    ["sea_​​village319"]: THREE.Mesh;
    ["sea_​​village318"]: THREE.Mesh;
    ["sea_​​village317"]: THREE.Mesh;
    ["sea_​​village316"]: THREE.Mesh;
    ["sea_​​village315"]: THREE.Mesh;
    ["sea_​​village314"]: THREE.Mesh;
    ["sea_​​village313"]: THREE.Mesh;
    ["sea_​​village312"]: THREE.Mesh;
    island3_house_1: THREE.Mesh;
    island3_eglise: THREE.Mesh;
    ["sea_​​village214"]: THREE.Mesh;
    ["sea_​​village213"]: THREE.Mesh;
    ["sea_​​village212"]: THREE.Mesh;
    ["sea_​​village211"]: THREE.Mesh;
    ["sea_​​village210"]: THREE.Mesh;
    ["sea_​​village208"]: THREE.Mesh;
    ["sea_​​village207"]: THREE.Mesh;
    ["sea_​​village206"]: THREE.Mesh;
    ["sea_​​village122"]: THREE.Mesh;
    ["sea_​​village121"]: THREE.Mesh;
    ["sea_​​village120"]: THREE.Mesh;
    ["sea_​​village119"]: THREE.Mesh;
    ["sea_​​village117"]: THREE.Mesh;
    ["sea_​​village116"]: THREE.Mesh;
    ["sea_​​village115"]: THREE.Mesh;
    ["sea_​​village114"]: THREE.Mesh;
    ["sea_​​village113"]: THREE.Mesh;
    ["sea_​​village112"]: THREE.Mesh;
    ["sea_​​village111"]: THREE.Mesh;
    ["sea_​​village090"]: THREE.Mesh;
    ["sea_​​village079"]: THREE.Mesh;
    ["sea_​​village078"]: THREE.Mesh;
    ["sea_​​village045"]: THREE.Mesh;
    ["sea_​​village039"]: THREE.Mesh;
    ["sea_​​village724"]: THREE.Mesh;
    ["sea_​​village723"]: THREE.Mesh;
    ["sea_​​village722"]: THREE.Mesh;
    ["sea_​​village721"]: THREE.Mesh;
    ["sea_​​village720"]: THREE.Mesh;
    ["sea_​​village719"]: THREE.Mesh;
    ["sea_​​village416"]: THREE.Mesh;
    ["sea_​​village415"]: THREE.Mesh;
    island1_house_1: THREE.Mesh;
    island1_house_2: THREE.Mesh;
    ["sea_​​village222"]: THREE.Mesh;
    ["sea_​​village167"]: THREE.Mesh;
    ["sea_​​village166"]: THREE.Mesh;
    ["sea_​​village165"]: THREE.Mesh;
    ["sea_​​village164"]: THREE.Mesh;
    ["sea_​​village163"]: THREE.Mesh;
    ["sea_​​village162"]: THREE.Mesh;
    ["sea_​​village161"]: THREE.Mesh;
    ["sea_​​village160"]: THREE.Mesh;
    ["sea_​​village159"]: THREE.Mesh;
    ["sea_​​village158"]: THREE.Mesh;
    ["sea_​​village157"]: THREE.Mesh;
    ["sea_​​village156"]: THREE.Mesh;
    ["sea_​​village027"]: THREE.Mesh;
    ["sea_​​village026"]: THREE.Mesh;
    ["sea_​​village025"]: THREE.Mesh;
    ["sea_​​village024"]: THREE.Mesh;
    ["sea_​​village733"]: THREE.Mesh;
    ["sea_​​village732"]: THREE.Mesh;
    ["sea_​​village731"]: THREE.Mesh;
    ["sea_​​village730"]: THREE.Mesh;
    ["sea_​​village729"]: THREE.Mesh;
    ["sea_​​village728"]: THREE.Mesh;
    ["sea_​​village727"]: THREE.Mesh;
    ["sea_​​village726"]: THREE.Mesh;
    ["sea_​​village725"]: THREE.Mesh;
    ["sea_​​village425"]: THREE.Mesh;
    ["sea_​​village424"]: THREE.Mesh;
    ["sea_​​village423"]: THREE.Mesh;
    ["sea_​​village422"]: THREE.Mesh;
    ["sea_​​village421"]: THREE.Mesh;
    ["sea_​​village420"]: THREE.Mesh;
    ["sea_​​village419"]: THREE.Mesh;
    ["sea_​​village418"]: THREE.Mesh;
    ["sea_​​village417"]: THREE.Mesh;
    island_center_house: THREE.Mesh;
    island1_2_pont: THREE.Mesh;
    island2_3_pont: THREE.Mesh;
  };
  materials: {
    ["low_poly_interior."]: THREE.MeshStandardMaterial;
    ["low_poly_interior..001"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..002"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..007"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..008"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..009"]: THREE.MeshStandardMaterial;
  };
};

export type GameLevelModelProps = JSX.IntrinsicElements["group"] & {
  onClick: (element: string) => void;
};

export const GameLevelModel: React.FC<GameLevelModelProps> = ({ onClick }) => {
  const { nodes, materials } = useGLTF("/scene/level/scene.glb") as GLTFResult;

  return (
    <group dispose={null}>
      <mesh
        geometry={nodes["sea_​​village900"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village899"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village898"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village897"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village896"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village895"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village894"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village893"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village892"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village891"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village890"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village889"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village888"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village887"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village886"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village885"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village884"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village883"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village882"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village881"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village880"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village879"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village878"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village877"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village876"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village875"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village874"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village873"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village872"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village871"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village870"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village869"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village868"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village867"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village866"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village865"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village864"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village863"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village862"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village861"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village860"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village859"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village858"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village857"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village856"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village855"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village854"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village853"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village852"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village851"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village850"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village849"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village848"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village847"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village846"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village845"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village844"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village843"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village842"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village841"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village840"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village839"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village838"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village837"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village836"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village835"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village834"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village833"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village832"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village831"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village830"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village829"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village828"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village827"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village826"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village825"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village824"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village823"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village822"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village821"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village820"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village819"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village818"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village817"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village816"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village815"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village814"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village813"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village812"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village811"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village810"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village809"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village808"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village807"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village806"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village805"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village804"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village803"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village802"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village801"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village800"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village799"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village798"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village797"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes.island3_house_3.geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes.island3_house_2.geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village794"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes.island3_chapelle.geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village792"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village791"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village790"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village789"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village788"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village787"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village786"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village785"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village784"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village783"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village782"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village781"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village780"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village779"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village778"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village777"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village776"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village775"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village774"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village773"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village772"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village771"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village770"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village769"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village768"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village762"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village761"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village760"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village759"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village758"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village662"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village661"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village660"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village659"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village658"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village657"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village656"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village655"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village654"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village653"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village652"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village651"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village650"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village649"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village648"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village647"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village646"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village645"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village644"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village643"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village642"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village641"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village640"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village639"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village638"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village637"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village636"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village635"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village634"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village633"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village632"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village631"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village630"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village629"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village628"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village627"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village626"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village625"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village622"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village621"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village620"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village619"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village618"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village617"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village616"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village602"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village599"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village598"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village597"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village596"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village595"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village594"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village593"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village592"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village591"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village590"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village589"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village543"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village542"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village531"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village530"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village525"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village524"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village398"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village397"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village396"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village395"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village394"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village393"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village392"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village391"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village390"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village389"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village388"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village387"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village386"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village385"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village384"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village383"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village382"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village381"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village380"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village379"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village378"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village377"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village376"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village375"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village374"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village373"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village372"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village371"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village370"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village342"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village341"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village340"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village339"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village338"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village337"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village336"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village335"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village334"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village333"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village332"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village331"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village330"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village329"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village327"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village326"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village325"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village324"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village323"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village322"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village321"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village320"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village319"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village318"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village317"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village316"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village315"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village314"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village313"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village312"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes.island3_house_1.geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes.island3_eglise.geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village214"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village213"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village212"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village211"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village210"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village208"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village207"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village206"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village122"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village121"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village120"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village119"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village117"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village116"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village115"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village114"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village113"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village112"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village111"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village090"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village079"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village078"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village045"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village039"].geometry}
        material={materials["low_poly_interior."]}
        position={[-70.879, -69.255, -154.177]}
        rotation={[0, 1.412, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village724"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village723"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village722"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village721"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village720"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village719"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village416"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village415"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes.island1_house_1.geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes.island1_house_2.geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village222"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village167"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village166"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village165"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village164"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village163"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village162"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village161"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village160"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village159"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village158"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village157"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village156"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village027"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village026"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village025"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village024"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[-63.813, -79.284, -37.77]}
        rotation={[Math.PI, -1.371, Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village733"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village732"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village731"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village730"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village729"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village728"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village727"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village726"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village725"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village425"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village424"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village423"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village422"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village421"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village420"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village419"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village418"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes["sea_​​village417"].geometry}
        material={materials["low_poly_interior..002"]}
        position={[-66.483, -79.117, -37.61]}
      />
      <mesh
        geometry={nodes.island_center_house.geometry}
        material={materials["low_poly_interior..007"]}
        position={[38.4, -69.311, -70.078]}
        rotation={[-Math.PI, 0.048, -Math.PI]}
        scale={1.004}
        onClick={() => onClick("island_center_house")}
      />
      <mesh
        geometry={nodes.island1_2_pont.geometry}
        material={materials["low_poly_interior..008"]}
        position={[-162.061, -79.359, -36.503]}
      />
      <mesh
        geometry={nodes.island2_3_pont.geometry}
        material={materials["low_poly_interior..009"]}
        position={[-193.981, -79.152, -37.845]}
      />
    </group>
  );
};

useGLTF.preload("/scene/level/scene.glb");
