/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\sceneAccueil.glb --types 
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["sea_​​village670"]: THREE.Mesh;
    ["sea_​​village669"]: THREE.Mesh;
    ["sea_​​village668"]: THREE.Mesh;
    ["sea_​​village667"]: THREE.Mesh;
    ["sea_​​village405"]: THREE.Mesh;
    ["sea_​​village404"]: THREE.Mesh;
    ["sea_​​village217"]: THREE.Mesh;
    ["sea_​​village144"]: THREE.Mesh;
    ["sea_​​village143"]: THREE.Mesh;
    ["sea_​​village142"]: THREE.Mesh;
    ["sea_​​village756"]: THREE.Mesh;
    ["sea_​​village755"]: THREE.Mesh;
    ["sea_​​village675"]: THREE.Mesh;
    ["sea_​​village674"]: THREE.Mesh;
    ["sea_​​village410"]: THREE.Mesh;
    ["sea_​​village409"]: THREE.Mesh;
    ["sea_​​village151"]: THREE.Mesh;
    ["sea_​​village023"]: THREE.Mesh;
    ["sea_​​village022"]: THREE.Mesh;
    ["sea_​​village021"]: THREE.Mesh;
    ["sea_​​village431"]: THREE.Mesh;
    ["sea_​​village430"]: THREE.Mesh;
    ["sea_​​village224"]: THREE.Mesh;
    ["sea_​​village001"]: THREE.Mesh;
    ["sea_​​village433"]: THREE.Mesh;
    ["sea_​​village183"]: THREE.Mesh;
    ["sea_​​village435"]: THREE.Mesh;
    ["sea_​​village002"]: THREE.Mesh;
    ["sea_​​village003"]: THREE.Mesh;
    ["sea_​​village004"]: THREE.Mesh;
    ["sea_​​village005"]: THREE.Mesh;
    ["sea_​​village739"]: THREE.Mesh;
    ["sea_​​village742"]: THREE.Mesh;
    ["sea_​​village740"]: THREE.Mesh;
    ["sea_​​village184"]: THREE.Mesh;
    ["sea_​​village031"]: THREE.Mesh;
    ["sea_​​village029"]: THREE.Mesh;
    ["sea_​​village743"]: THREE.Mesh;
    ["sea_​​village006"]: THREE.Mesh;
  };
  materials: {
    ["low_poly_interior..001"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..003"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..005"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..006"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..008"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..009"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..010"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..011"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..012"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..013"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..014"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..015"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..016"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..017"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..018"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..019"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..021"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..022"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..023"]: THREE.MeshStandardMaterial;
    ["low_poly_interior..024"]: THREE.MeshStandardMaterial;
  };
  // animations: GLTFAction[];
};

export type SceneAccueilModelProps = JSX.IntrinsicElements["group"];

export const SceneAccueilModel: React.FC<SceneAccueilModelProps> = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/scene/sceneAccueil.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["sea_​​village670"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[48.502, -58.471, -16.637]}
        rotation={[0, 0.547, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village669"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[48.502, -58.471, -16.637]}
        rotation={[0, 0.547, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village668"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[48.502, -58.471, -16.637]}
        rotation={[0, 0.547, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village667"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[48.502, -58.471, -16.637]}
        rotation={[0, 0.547, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village405"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[48.502, -58.471, -16.637]}
        rotation={[0, 0.547, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village404"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[48.502, -58.471, -16.637]}
        rotation={[0, 0.547, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village217"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[48.502, -58.471, -16.637]}
        rotation={[0, 0.547, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village144"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[48.502, -58.471, -16.637]}
        rotation={[0, 0.547, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village143"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[48.502, -58.471, -16.637]}
        rotation={[0, 0.547, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village142"].geometry}
        material={materials["low_poly_interior..001"]}
        position={[48.502, -58.471, -16.637]}
        rotation={[0, 0.547, 0]}
      />
      <mesh
        geometry={nodes["sea_​​village756"].geometry}
        material={materials["low_poly_interior..003"]}
        position={[17.533, -58.566, 8.589]}
      />
      <mesh
        geometry={nodes["sea_​​village755"].geometry}
        material={materials["low_poly_interior..003"]}
        position={[17.533, -58.566, 8.589]}
      />
      <mesh
        geometry={nodes["sea_​​village675"].geometry}
        material={materials["low_poly_interior..003"]}
        position={[17.533, -58.566, 8.589]}
      />
      <mesh
        geometry={nodes["sea_​​village674"].geometry}
        material={materials["low_poly_interior..003"]}
        position={[17.533, -58.566, 8.589]}
      />
      <mesh
        geometry={nodes["sea_​​village410"].geometry}
        material={materials["low_poly_interior..003"]}
        position={[17.533, -58.566, 8.235]}
      />
      <mesh
        geometry={nodes["sea_​​village409"].geometry}
        material={materials["low_poly_interior..003"]}
        position={[17.533, -58.566, 8.589]}
      />
      <mesh
        geometry={nodes["sea_​​village151"].geometry}
        material={materials["low_poly_interior..003"]}
        position={[17.533, -58.566, 8.589]}
      />
      <mesh
        geometry={nodes["sea_​​village023"].geometry}
        material={materials["low_poly_interior..003"]}
        position={[17.533, -58.566, 8.589]}
      />
      <mesh
        geometry={nodes["sea_​​village022"].geometry}
        material={materials["low_poly_interior..003"]}
        position={[17.533, -58.566, 8.589]}
      />
      <mesh
        geometry={nodes["sea_​​village021"].geometry}
        material={materials["low_poly_interior..003"]}
        position={[17.533, -58.566, 8.589]}
      />
      <mesh
        geometry={nodes["sea_​​village431"].geometry}
        material={materials["low_poly_interior..005"]}
        position={[-44.48, -58.871, 17.97]}
      />
      <mesh
        geometry={nodes["sea_​​village430"].geometry}
        material={materials["low_poly_interior..005"]}
        position={[-44.48, -58.85, 17.97]}
      />
      <mesh
        geometry={nodes["sea_​​village224"].geometry}
        material={materials["low_poly_interior..006"]}
        position={[78.455, -69.219, -95.222]}
        rotation={[Math.PI, -0.819, 3.126]}
        scale={0.901}
      />
      <mesh
        geometry={nodes["sea_​​village001"].geometry}
        material={materials["low_poly_interior..008"]}
        position={[-43.526, 1.074, 55.776]}
        rotation={[-Math.PI, 1.523, -Math.PI]}
      />
      <mesh
        geometry={nodes["sea_​​village433"].geometry}
        material={materials["low_poly_interior..009"]}
        position={[-21.511, -18.15, 4.044]}
        scale={0.276}
      />
      <mesh
        geometry={nodes["sea_​​village183"].geometry}
        material={materials["low_poly_interior..010"]}
        position={[-98.182, -72.128, 15.395]}
        scale={0.917}
      />
      <mesh geometry={nodes["sea_​​village435"].geometry} material={materials["low_poly_interior..011"]} />
      <mesh
        geometry={nodes["sea_​​village002"].geometry}
        material={materials["low_poly_interior..012"]}
        position={[-50.532, -30.137, 6.021]}
        scale={0.447}
      />
      <mesh
        geometry={nodes["sea_​​village003"].geometry}
        material={materials["low_poly_interior..013"]}
        position={[-49.954, -30.137, 6.849]}
        scale={0.447}
      />
      <mesh
        geometry={nodes["sea_​​village004"].geometry}
        material={materials["low_poly_interior..014"]}
        position={[-45.966, -30.128, 6.334]}
        scale={0.447}
      />
      <mesh
        geometry={nodes["sea_​​village005"].geometry}
        material={materials["low_poly_interior..015"]}
        position={[-46.423, -30.133, 7.114]}
        scale={0.447}
      />
      <mesh
        geometry={nodes["sea_​​village739"].geometry}
        material={materials["low_poly_interior..016"]}
        position={[-52.18, -30.927, 8.635]}
        scale={0.537}
      />
      <mesh
        geometry={nodes["sea_​​village742"].geometry}
        material={materials["low_poly_interior..017"]}
        position={[-41.095, -26.833, 9.361]}
        scale={0.468}
      />
      <mesh
        geometry={nodes["sea_​​village740"].geometry}
        material={materials["low_poly_interior..018"]}
        position={[-77.45, -44.731, 14.834]}
        scale={0.767}
      />
      <mesh
        geometry={nodes["sea_​​village184"].geometry}
        material={materials["low_poly_interior..019"]}
        position={[-77.612, -57.989, 11.07]}
        scale={0.739}
      />
      <mesh
        geometry={nodes["sea_​​village031"].geometry}
        material={materials["low_poly_interior..021"]}
        position={[-53.047, -36.844, -1.78]}
        scale={0.726}
      />
      <mesh
        geometry={nodes["sea_​​village029"].geometry}
        material={materials["low_poly_interior..022"]}
        position={[-28.285, -35.423, -3.141]}
        scale={0.67}
      />
      <mesh
        geometry={nodes["sea_​​village743"].geometry}
        material={materials["low_poly_interior..023"]}
        position={[-62.879, -35.341, 11.576]}
        scale={0.607}
      />
      <mesh
        geometry={nodes["sea_​​village006"].geometry}
        material={materials["low_poly_interior..024"]}
        position={[9.662, -42.238, 13.902]}
        scale={0.722}
      />
    </group>
  );
};

useGLTF.preload("/scene/sceneAccueil.glb");
